# Generated by Django 5.1 on 2024-11-14 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('inn', models.CharField(max_length=12, unique=True)),
                ('ogrn', models.CharField(max_length=15, unique=True)),
                ('kpp', models.CharField(max_length=9)),
                ('r_s', models.CharField(max_length=20)),
                ('bank', models.CharField(max_length=255)),
                ('bik', models.CharField(max_length=9)),
                ('k_s', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('ceo_title', models.CharField(max_length=100)),
                ('ceo_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Юридические лица',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=5, null=True)),
                ('date', models.DateField()),
                ('amount', models.IntegerField(default=0)),
                ('payed_amount', models.IntegerField(default=0)),
                ('shipping_amount', models.IntegerField(default=0)),
                ('montage_amount', models.IntegerField(default=0)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('year', models.PositiveIntegerField(editable=False)),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_entity', to='erp_main.legalentity')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_order_number', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_file', models.FileField(upload_to='uploads/')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='erp_main.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='OrderChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_internal_order_number', models.CharField(max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='erp_main.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_kind', models.CharField(choices=[('door', 'Дверь'), ('gate', 'Ворота'), ('hatch', 'Люк'), ('transom', 'Фрамуга'), ('dobor', 'Добор'), ('others', 'Прочее')], max_length=100, null=True)),
                ('p_type', models.CharField(choices=[('tech', 'тех.'), ('ei-60', 'EI-60'), ('eis-60', 'EIS-60'), ('eiws-60', 'EIWS-60'), ('flat', 'квартир.'), ('one_layer', 'однолист.'), ('revision', 'ревиз.')], max_length=100)),
                ('p_construction', models.CharField(blank=True, choices=[('SK', 'старый конструктив'), ('NK', 'новый конструктив')], max_length=100, null=True)),
                ('p_width', models.DecimalField(decimal_places=0, max_digits=10)),
                ('p_height', models.DecimalField(decimal_places=0, max_digits=10)),
                ('p_open', models.CharField(blank=True, max_length=2, null=True)),
                ('p_active_trim', models.CharField(blank=True, max_length=5, null=True)),
                ('p_furniture', models.CharField(blank=True, max_length=100, null=True)),
                ('p_ral', models.CharField(blank=True, max_length=100, null=True)),
                ('p_platband', models.CharField(blank=True, max_length=100, null=True)),
                ('p_door_closer', models.CharField(blank=True, max_length=100, null=True)),
                ('p_step', models.CharField(blank=True, max_length=100, null=True)),
                ('p_metal', models.CharField(blank=True, max_length=100, null=True)),
                ('p_vent_grate', models.CharField(blank=True, max_length=100, null=True)),
                ('p_plate', models.CharField(blank=True, max_length=100, null=True)),
                ('p_glass', models.CharField(blank=True, max_length=100, null=True)),
                ('p_status', models.CharField(choices=[('in_query', 'в очереди'), ('product', 'запущен'), ('ready', 'готов'), ('shipped', 'отгружен'), ('canceled', 'отменен'), ('stopped', 'остановлен'), ('changed', 'изменен')], default='in_query', max_length=15)),
                ('position_num', models.CharField(max_length=5)),
                ('nameplate_range', models.CharField(blank=True, max_length=100, null=True)),
                ('p_quantity', models.IntegerField(default=1)),
                ('p_comment', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('firm_plate', models.BooleanField(default=True)),
                ('mounting_plates', models.CharField(blank=True, default=False, max_length=100, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp_main.order')),
            ],
        ),
        migrations.CreateModel(
            name='GlassInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, choices=[('pp', 'п/п'), ('spo', 'СПО'), ('zkl', 'закаленное'), ('sp_2', '2-кам. стеклопакет'), ('triplex', 'триплекс')], max_length=20, null=True)),
                ('option', models.CharField(blank=True, choices=[('a1_1', 'пленка A1 с одной стороны'), ('a1_2', 'пленка A1 с двух сторон'), ('a2_1', 'пленка A2 с одной стороны'), ('a2_2', 'пленка A2 с двух сторон'), ('a3_1', 'пленка A3 с одной стороны'), ('a3_2', 'пленка A3 с двух сторон')], max_length=20, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('depth', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('not_ordered', 'не заказано'), ('ordered', 'заказано'), ('ready', 'изготовлено'), ('received', 'получено')], max_length=100, null=True)),
                ('comment', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('order_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glasses', to='erp_main.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, choices=[('ooo', 'ООО'), ('ao', 'АО'), ('zao', 'ЗАО'), ('ip', 'ИП')], max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('name_fl', models.CharField(blank=True, max_length=15, null=True)),
                ('ceo_footing', models.CharField(choices=[('ustav', 'устава'), ('attorney', 'доверенности')], max_length=30)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('inn', models.CharField(blank=True, max_length=15, null=True)),
                ('ogrn', models.CharField(blank=True, max_length=15, null=True)),
                ('kpp', models.CharField(blank=True, max_length=15, null=True)),
                ('r_s', models.CharField(blank=True, max_length=25, null=True)),
                ('bank', models.CharField(blank=True, max_length=300, null=True)),
                ('bik', models.CharField(blank=True, max_length=10, null=True)),
                ('k_s', models.CharField(blank=True, max_length=25, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ceo_title', models.CharField(blank=True, max_length=30, null=True)),
                ('ceo_name', models.CharField(blank=True, max_length=150, null=True)),
                ('contracts', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='erp_main.organization'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('number', 'legal_entity', 'year'), name='unique_field_combination'),
        ),
    ]
