# Generated by Django 5.1 on 2024-08-29 07:11

import django.db.models.deletion
import erp_main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montage_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('legal_entity', models.CharField(choices=[('P', 'Палани'), ('PI', 'Палани Инжиниринг'), ('PD', 'Палани Дистрибуция'), ('GP', 'Глобал Палани'), ('DMM', 'Двери металл-М')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('internal_order_number', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_file', models.FileField(blank=True, null=True, upload_to=erp_main.models.order_file_upload_to)),
                ('firm_plate', models.BooleanField(default=True)),
                ('mounting_plates', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_internal_order_number', models.CharField(max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='erp_main.order')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inn', models.CharField(max_length=15)),
                ('last_order_date', models.DateField()),
                ('user', models.ManyToManyField(related_name='organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_kind', models.CharField(choices=[('door', 'дверь'), ('gate', 'ворота'), ('hatch', 'люк'), ('transom', 'фрамуга'), ('dobor', 'добор'), ('others', 'прочее')], max_length=100)),
                ('p_type', models.CharField(choices=[('tech', 'тех.'), ('ei-60', 'EI-60'), ('eis-60', 'EIS-60'), ('eiws-60', 'EIWS-60'), ('flat', 'квартир.'), ('one_layer', 'однолист.'), ('revision', 'ревиз.')], max_length=100)),
                ('p_construction', models.CharField(blank=True, choices=[('SK', 'старый конструктив'), ('NK', 'новый конструктив')], max_length=100, null=True)),
                ('p_width', models.DecimalField(decimal_places=0, max_digits=10)),
                ('p_height', models.DecimalField(decimal_places=0, max_digits=10)),
                ('p_open', models.CharField(blank=True, max_length=2, null=True)),
                ('p_active_trim', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('p_furniture', models.JSONField(blank=True, null=True)),
                ('p_ral', models.JSONField(blank=True, null=True)),
                ('p_platband', models.JSONField(blank=True, null=True)),
                ('p_door_closer', models.JSONField(blank=True, null=True)),
                ('p_step', models.CharField(blank=True, max_length=100, null=True)),
                ('p_metal', models.JSONField()),
                ('p_vent_grate', models.JSONField(blank=True, null=True)),
                ('p_plate', models.JSONField(blank=True, null=True)),
                ('p_glass', models.CharField(blank=True, max_length=255, null=True)),
                ('p_others', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(max_length=15)),
                ('position_num', models.CharField(max_length=5)),
                ('nameplate_range', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_main.invoice')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp_main.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_main.organization')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_main.organization'),
        ),
    ]
