# Generated by Django 5.1 on 2024-11-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
