# Generated by Django 5.1 on 2024-08-29 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='comment',
            new_name='p_comment',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='p_quantity',
        ),
    ]
