# Generated by Django 5.2.8 on 2025-11-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='content_type',
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Расчетный счет'),
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название банка'),
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='bik',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='correspondent_account',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Корреспондентский счет'),
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='internallegalentity',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Расчетный счет'),
        ),
        migrations.AddField(
            model_name='internallegalentity',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название банка'),
        ),
        migrations.AddField(
            model_name='internallegalentity',
            name='bik',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='internallegalentity',
            name='correspondent_account',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Корреспондентский счет'),
        ),
        migrations.AddField(
            model_name='internallegalentity',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Расчетный счет'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название банка'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='bik',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='correspondent_account',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Корреспондентский счет'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='physicalperson',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='BankDetails',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
    ]
