# Generated by Django 5.1 on 2024-11-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_files',
            field=models.FileField(blank=True, null=True, upload_to='uploads/invoices'),
        ),
        migrations.AddField(
            model_name='organization',
            name='contracts',
            field=models.FileField(blank=True, null=True, upload_to='uploads/contracts'),
        ),
    ]
