# Generated by Django 5.1.5 on 2025-11-11 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nameplate',
        ),
    ]
