# Generated by Django 5.1 on 2024-08-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0002_rename_comment_orderitem_p_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='firm_plate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mounting_plates',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='firm_plate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='mounting_plates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_kind',
            field=models.CharField(choices=[('door', 'дверь'), ('gate', 'ворота'), ('hatch', 'люк'), ('transom', 'фрамуга'), ('dobor', 'добор'), ('others', 'прочее')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_metal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
