# Generated by Django 5.2.8 on 2025-11-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0002_remove_email_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internallegalentity',
            name='type',
            field=models.CharField(choices=[('LEGAL', 'ООО'), ('INDIVIDUAL', 'ИП'), ('PERSON', 'Без счета')], default='LEGAL', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internallegalentity',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название ЮЛ'),
        ),
    ]
