# Generated by Django 5.1 on 2024-10-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0002_alter_orderitem_p_active_trim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='legal_entity',
            field=models.CharField(choices=[('P', 'Палани'), ('PI', 'Палани Инжиниринг'), ('PD', 'Палани Дистрибуция'), ('GP', 'Глобал Палани'), ('DMM', 'Двери металл-М'), ('FL', 'Прочее')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_kind',
            field=models.CharField(choices=[('door', 'Дверь'), ('gate', 'Ворота'), ('hatch', 'Люк'), ('transom', 'Фрамуга'), ('dobor', 'Добор'), ('others', 'Прочее')], max_length=100, null=True),
        ),
    ]
