# Generated by Django 5.1.5 on 2025-11-11 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0002_delete_nameplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nameplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_value', models.IntegerField(blank=True, null=True)),
                ('end_value', models.IntegerField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('certificate', models.ForeignKey(db_column='certificate_id', on_delete=django.db.models.deletion.CASCADE, related_name='nameplates', to='erp_main.certificate')),
                ('order_item', models.ForeignKey(db_column='order_item_id', on_delete=django.db.models.deletion.CASCADE, related_name='nameplates', to='erp_main.orderitem')),
            ],
            options={
                'verbose_name': 'Шильд',
                'verbose_name_plural': 'Шильды',
                'db_table': 'erp_main_nameplate',
            },
        ),
    ]
