# Generated by Django 5.1 on 2024-11-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0002_invoice_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='change_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
