# Generated by Django 5.1 on 2024-10-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0003_alter_invoice_legal_entity_alter_orderitem_p_kind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='last_order_date',
            new_name='create_at',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='montage_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payed_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shipping_amount',
            field=models.IntegerField(default=0),
        ),
    ]
