# Generated by Django 5.2.8 on 2025-11-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0003_internallegalentity_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internallegalentity',
            name='address',
        ),
        migrations.AddField(
            model_name='internallegalentity',
            name='legal_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='internallegalentity',
            name='postal_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Почтовый адрес'),
        ),
        migrations.AlterField(
            model_name='internallegalentity',
            name='ceo_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО руководителя'),
        ),
        migrations.AlterField(
            model_name='internallegalentity',
            name='ceo_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность руководителя'),
        ),
        migrations.AlterField(
            model_name='internallegalentity',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='internallegalentity',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='internallegalentity',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='internallegalentity',
            name='ogrn',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='internallegalentity',
            name='type',
            field=models.CharField(choices=[('LEGAL', 'ООО'), ('INDIVIDUAL', 'ИП'), ('WITHOUT_INVOICE', 'Без выставления счета')], max_length=20, verbose_name='ТИП'),
        ),
    ]
