# Generated by Django 5.1 on 2024-11-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0003_alter_invoice_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='p_others',
            new_name='p_glass_status',
        ),
    ]
