# Generated by Django 5.1 on 2024-12-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0003_invoice_change_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='workshop',
            field=models.IntegerField(default=0),
        ),
    ]
