# Generated by Django 5.1 on 2025-01-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0004_orderitem_workshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_width',
            field=models.IntegerField(default=0),
        ),
    ]
