# Generated by Django 5.1.5 on 2025-11-13 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0004_contracttemplate_remove_organization_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttemplate',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('legal_entity', 'Юридическое лицо'), ('individual_entrepreneur', 'Индивидуальный предприниматель'), ('physical_person', 'Физическое лицо')], default='legal_entity', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='footing_type',
            field=models.CharField(blank=True, choices=[('ustav', 'устава'), ('attorney', 'доверенности')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_main.legalentity'),
        ),
        migrations.AddField(
            model_name='organization',
            name='attorney_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='attorney_file',
            field=models.FileField(blank=True, null=True, upload_to='attorney_files/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='attorney_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='history',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='organization',
            name='ogrnip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('legal_entity', 'Юридическое лицо'), ('individual_entrepreneur', 'Индивидуальный предприниматель'), ('physical_person', 'Физическое лицо')], default='legal_entity', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='passport_scan',
            field=models.FileField(blank=True, null=True, upload_to='passport_scans/'),
        ),
        migrations.AlterField(
            model_name='contracttemplate',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('ooo', 'ООО'), ('ao', 'АО'), ('zao', 'ЗАО')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ceo_footing',
            field=models.CharField(blank=True, choices=[('ustav', 'устава'), ('attorney', 'доверенности')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='kind',
            field=models.CharField(blank=True, choices=[('ooo', 'ООО'), ('ao', 'АО'), ('zao', 'ЗАО')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name_fl',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
