# Generated by Django 5.2.8 on 2025-11-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0004_remove_internallegalentity_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internallegalentity',
            name='ceo_title',
            field=models.CharField(blank=True, choices=[('director', 'Директор'), ('general_director', 'Генеральный директор')], max_length=20, null=True, verbose_name='Должность руководителя'),
        ),
    ]
