# Generated by Django 5.1 on 2024-10-14 08:25

import django.core.validators
import erp_main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0004_rename_last_order_date_organization_create_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='create_at',
        ),
        migrations.AddField(
            model_name='organization',
            name='name_fl',
            field=models.CharField(default=None, max_length=15, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s]+$')]),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(default=None, max_length=15, validators=[erp_main.models.validate_numeric_only]),
        ),
    ]
