# Generated by Django 5.1 on 2024-11-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0004_rename_p_others_orderitem_p_glass_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_files',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/invoices'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_glass_status',
            field=models.CharField(choices=[('not_ordered', 'не заказано')], default='not_ordered', max_length=15),
        ),
    ]
