# Generated by Django 5.2.8 on 2026-01-22 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0005_alter_internallegalentity_ceo_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['order', 'position_num'], 'verbose_name': 'Позиция заказа', 'verbose_name_plural': 'Позиции заказа'},
        ),
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_field_combination',
        ),
        migrations.AlterField(
            model_name='glassinfo',
            name='order_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glasses', to='erp_main.orderitem'),
        ),
        migrations.AlterField(
            model_name='internallegalentity',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='internallegalentity',
            name='type',
            field=models.CharField(choices=[('LEGAL', 'ООО'), ('INDIVIDUAL', 'ИП'), ('WITHOUT_INVOICE', 'Без выставления счета')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='firm_plate',
            field=models.BooleanField(default=False, verbose_name='фирменный шильд'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_kind',
            field=models.CharField(choices=[('door', 'Дверь'), ('gate', 'Ворота'), ('hatch', 'Люк'), ('transom', 'Фрамуга'), ('dobor', 'Добор'), ('others', 'Прочее'), ('wickit', 'Калитка')], max_length=15, null=True, verbose_name='вид изделия'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_open',
            field=models.CharField(blank=True, choices=[('right', 'R'), ('left', 'L')], max_length=100, null=True, verbose_name='открывание'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_type',
            field=models.CharField(choices=[('tech', 'тех.'), ('ei-60', 'EI-60'), ('eis-60', 'EIS-60'), ('eiws-60', 'EIWS-60'), ('flat', 'квартир.'), ('one_layer', 'однолист.'), ('revision', 'ревиз.'), ('None', '')], max_length=10, verbose_name='тип изделия'),
        ),
    ]
