# Generated by Django 5.1 on 2025-01-14 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0005_passport_alter_orderitem_p_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='firm_plate',
            field=models.BooleanField(default=True, verbose_name='фирменный шильд'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='mounting_plates',
            field=models.CharField(blank=True, default=False, max_length=100, null=True, verbose_name='монтажные уши'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='nameplate_range',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='номера шильдов'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp_main.order', verbose_name='заказ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_active_trim',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='ширина активной створки'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_comment',
            field=models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_construction',
            field=models.CharField(blank=True, choices=[('SK', 'старый конструктив'), ('NK', 'новый конструктив')], max_length=100, null=True, verbose_name='конструктив изделия'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_door_closer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='доводчик'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_furniture',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='фурнитура'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_glass',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='остекление'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_height',
            field=models.IntegerField(default=0, verbose_name='высота изделия'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_kind',
            field=models.CharField(choices=[('door', 'Дверь'), ('gate', 'Ворота'), ('hatch', 'Люк'), ('transom', 'Фрамуга'), ('dobor', 'Добор'), ('others', 'Прочее')], max_length=100, null=True, verbose_name='вид изделия'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_metal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='толщина металла'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_open',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='открывание'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_platband',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='наличник'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_plate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='отбойная пластина'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_quantity',
            field=models.IntegerField(default=1, verbose_name='количество изделий'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_ral',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RAL'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_status',
            field=models.CharField(choices=[('in_query', 'в очереди'), ('product', 'запущен'), ('ready', 'готов'), ('shipped', 'отгружен'), ('canceled', 'отменен'), ('stopped', 'остановлен'), ('changed', 'изменен')], default='in_query', max_length=15, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_step',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='порог'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_type',
            field=models.CharField(choices=[('tech', 'тех.'), ('ei-60', 'EI-60'), ('eis-60', 'EIS-60'), ('eiws-60', 'EIWS-60'), ('flat', 'квартир.'), ('one_layer', 'однолист.'), ('revision', 'ревиз.')], max_length=100, verbose_name='тип изделия'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_vent_grate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='вент.решетка'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_width',
            field=models.IntegerField(default=0, verbose_name='ширина изделия'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='position_num',
            field=models.CharField(max_length=5, verbose_name='номер позиции'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='workshop',
            field=models.IntegerField(default=0, verbose_name='цех'),
        ),
    ]
