# Generated by Django 5.2.8 on 2025-12-09 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0005_alter_internallegalentity_ceo_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Код для счета и заявки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Розничная цена')),
                ('base_order_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена в заказе')),
                ('image', models.ImageField(blank=True, null=True, upload_to='furniture/%Y/%m/%d/', verbose_name='изображение')),
                ('fireproof', models.BooleanField(default=None)),
                ('vendor_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Артикул')),
                ('supplier', models.CharField(blank=True, max_length=50, null=True, verbose_name='Поставщик')),
                ('purchase_price', models.IntegerField(blank=True, null=True, verbose_name='Закупочная цена')),
                ('quantity_in_stock', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, verbose_name='Зарезервировано')),
                ('min_stock', models.PositiveIntegerField(default=10, verbose_name='Минимальный запас')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Дверная ручка',
                'verbose_name_plural': 'Дверные ручки',
            },
        ),
        migrations.CreateModel(
            name='DoorLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Код для счета и заявки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Розничная цена')),
                ('base_order_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена в заказе')),
                ('image', models.ImageField(blank=True, null=True, upload_to='furniture/%Y/%m/%d/', verbose_name='изображение')),
                ('fireproof', models.BooleanField(default=None)),
                ('vendor_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Артикул')),
                ('supplier', models.CharField(blank=True, max_length=50, null=True, verbose_name='Поставщик')),
                ('purchase_price', models.IntegerField(blank=True, null=True, verbose_name='Закупочная цена')),
                ('quantity_in_stock', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, verbose_name='Зарезервировано')),
                ('min_stock', models.PositiveIntegerField(default=10, verbose_name='Минимальный запас')),
            ],
            options={
                'verbose_name': 'Дверной замок',
                'verbose_name_plural': 'Дверные замки',
            },
        ),
        migrations.CreateModel(
            name='LockCylinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Код для счета и заявки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Розничная цена')),
                ('base_order_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена в заказе')),
                ('image', models.ImageField(blank=True, null=True, upload_to='furniture/%Y/%m/%d/', verbose_name='изображение')),
                ('fireproof', models.BooleanField(default=None)),
                ('vendor_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Артикул')),
                ('supplier', models.CharField(blank=True, max_length=50, null=True, verbose_name='Поставщик')),
                ('purchase_price', models.IntegerField(blank=True, null=True, verbose_name='Закупочная цена')),
                ('quantity_in_stock', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, verbose_name='Зарезервировано')),
                ('min_stock', models.PositiveIntegerField(default=10, verbose_name='Минимальный запас')),
            ],
            options={
                'verbose_name': 'Цилиндровый механизм',
                'verbose_name_plural': 'Цилиндровые механизмы',
            },
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['order', 'position_num'], 'verbose_name': 'Позиция заказа', 'verbose_name_plural': 'Позиции заказа'},
        ),
        migrations.AlterField(
            model_name='internallegalentity',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='internallegalentity',
            name='type',
            field=models.CharField(choices=[('LEGAL', 'ООО'), ('INDIVIDUAL', 'ИП'), ('WITHOUT_INVOICE', 'Без выставления счета')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_active_trim',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ширина активной створки'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_kind',
            field=models.CharField(choices=[('door', 'Дверь'), ('gate', 'Ворота'), ('hatch', 'Люк'), ('transom', 'Фрамуга'), ('dobor', 'Добор'), ('others', 'Прочее'), ('small_gate', 'Калитка')], max_length=15, null=True, verbose_name='вид изделия'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_open',
            field=models.CharField(blank=True, choices=[('right', 'R'), ('left', 'L')], max_length=100, null=True, verbose_name='открывание'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p_type',
            field=models.CharField(choices=[('tech', 'тех.'), ('ei-60', 'EI-60'), ('eis-60', 'EIS-60'), ('eiws-60', 'EIWS-60'), ('flat', 'квартир.'), ('one_layer', 'однолист.'), ('revision', 'ревиз.'), ('None', '')], max_length=10, verbose_name='тип изделия'),
        ),
        migrations.CreateModel(
            name='FurnitureKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Наименование комплекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='furniture_kit', to='erp_main.orderitem', verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Комплект фурнитуры',
                'verbose_name_plural': 'Комплекты фурнитуры',
            },
        ),
        migrations.CreateModel(
            name='FurnitureKitHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('door_handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_main.doorhandle')),
                ('furniture_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_main.furniturekit')),
            ],
            options={
                'verbose_name': 'Ручка в комплекте',
                'verbose_name_plural': 'Ручки в комплекте',
                'unique_together': {('furniture_kit', 'door_handle')},
            },
        ),
        migrations.AddField(
            model_name='furniturekit',
            name='handles',
            field=models.ManyToManyField(blank=True, related_name='furniture_kits', through='erp_main.FurnitureKitHandle', to='erp_main.doorhandle', verbose_name='Ручки'),
        ),
        migrations.CreateModel(
            name='FurnitureKitLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('door_lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_main.doorlock')),
                ('furniture_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_main.furniturekit')),
            ],
            options={
                'verbose_name': 'Замок в комплекте',
                'verbose_name_plural': 'Замки в комплекте',
                'unique_together': {('furniture_kit', 'door_lock')},
            },
        ),
        migrations.AddField(
            model_name='furniturekit',
            name='locks',
            field=models.ManyToManyField(blank=True, related_name='furniture_kits', through='erp_main.FurnitureKitLock', to='erp_main.doorlock', verbose_name='Замки'),
        ),
        migrations.CreateModel(
            name='FurnitureKitCylinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('furniture_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_main.furniturekit')),
                ('lock_cylinder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_main.lockcylinder')),
            ],
            options={
                'verbose_name': 'Ц/м в комплекте',
                'verbose_name_plural': 'Ц/м в комплекте',
                'unique_together': {('furniture_kit', 'lock_cylinder')},
            },
        ),
        migrations.AddField(
            model_name='furniturekit',
            name='cylinders',
            field=models.ManyToManyField(blank=True, related_name='furniture_kits', through='erp_main.FurnitureKitCylinder', to='erp_main.lockcylinder', verbose_name='ц/м'),
        ),
    ]
