# Generated by Django 5.1 on 2024-11-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0005_remove_invoice_invoice_files_invoice_invoice_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contracts',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
    ]
