# Generated by Django 5.1 on 2024-10-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0005_remove_organization_create_at_organization_name_fl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name_fl',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
