# Generated by Django 5.1 on 2025-01-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0006_alter_orderitem_firm_plate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment_changes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
