# Generated by Django 5.1 on 2024-10-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0006_alter_organization_inn_alter_organization_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(blank=True, default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name_fl',
            field=models.CharField(blank=True, default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=15),
        ),
    ]
