# Generated by Django 5.2.8 on 2026-01-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0006_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='p_active_trim',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ширина активной створки'),
        ),
    ]
