# Generated by Django 5.1 on 2025-01-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0007_order_comment_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comment_changes',
        ),
        migrations.RemoveField(
            model_name='orderchangehistory',
            name='previous_internal_order_number',
        ),
        migrations.AddField(
            model_name='orderchangehistory',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderchangehistory',
            name='order_file',
            field=models.FileField(default=None, upload_to='uploads/changes/'),
            preserve_default=False,
        ),
    ]
