# Generated by Django 5.2.8 on 2026-01-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0007_alter_orderitem_p_active_trim'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualentrepreneur',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
