# Generated by Django 5.2.8 on 2026-02-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0008_individualentrepreneur_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
