# Generated by Django 5.1 on 2024-10-16 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0008_alter_organization_inn_alter_organization_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='readiness',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
