# Generated by Django 5.2.8 on 2026-02-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0008_individualentrepreneur_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='numbers',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
