# Generated by Django 5.2.8 on 2026-02-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0009_order_numbers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='numbers',
            new_name='number',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['number'], name='erp_main_or_number_7bd3fd_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='erp_main_or_created_d4ef4c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['due_date', 'created_at'], name='erp_main_or_due_dat_890d54_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['invoice'], name='erp_main_or_invoice_a13065_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('number', 'internal_legal_entity', 'year'), name='unique_field_combination'),
        ),
    ]
