# Generated by Django 5.1 on 2024-10-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0009_order_comment_order_readiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='readiness',
            field=models.IntegerField(default=1),
        ),
    ]
