# Generated by Django 5.1 on 2024-10-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0010_alter_order_comment_alter_order_readiness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='readiness',
        ),
        migrations.AddField(
            model_name='order',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
