# Generated by Django 5.1 on 2024-10-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0011_remove_order_readiness_order_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
