# Generated by Django 5.1.5 on 2025-03-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0013_invoice_closing_document_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipment_type',
            field=models.CharField(choices=[('pickup', 'самовывоз'), ('our', 'наша'), ('tk', 'ТК')], default='pickup', max_length=20),
        ),
    ]
