# Generated by Django 5.1.5 on 2025-04-22 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0014_shipment_shipment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='city',
            new_name='comments',
        ),
    ]
