# Generated by Django 5.1.5 on 2025-04-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_main', '0015_rename_city_shipment_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderchangehistory',
            name='order_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
