# Generated by Django 5.2.8 on 2025-11-20 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp_main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CP',
            fields=[
                ('orderitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erp_main.orderitem')),
                ('date', models.DateField()),
            ],
            bases=('erp_main.orderitem',),
        ),
        migrations.CreateModel(
            name='StandardPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_1', models.JSONField()),
                ('door_2', models.JSONField()),
                ('wide_door_1', models.JSONField()),
                ('hatch_1', models.JSONField()),
                ('wide_hatch_1', models.JSONField()),
                ('not_standard', models.JSONField()),
                ('gate', models.JSONField()),
                ('wide_gate', models.JSONField()),
                ('transom', models.JSONField()),
                ('dobor', models.JSONField()),
                ('door_panel', models.JSONField()),
                ('lock', models.JSONField()),
                ('handle', models.JSONField()),
                ('c_m', models.JSONField()),
                ('door_closer', models.JSONField()),
                ('metal', models.JSONField()),
                ('ral', models.JSONField()),
                ('vent_grate', models.JSONField()),
                ('plate', models.JSONField()),
                ('glass', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_items', models.IntegerField(default=0)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_main.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalculationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('door_type', models.CharField(choices=[('internal', 'Межкомнатная'), ('external', 'Входная'), ('fire', 'Противопожарная'), ('armored', 'Бронированная')], default='internal', max_length=20)),
                ('status', models.IntegerField(choices=[(0, 'Черновик'), (1, 'На производстве'), (2, 'Готов к отгрузке'), (3, 'Отгружен'), (4, 'Отменен')], default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='calculation.calculation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PersonalPrice',
            fields=[
                ('standardprice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calculation.standardprice')),
                ('default_margin', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='erp_main.organization')),
            ],
            bases=('calculation.standardprice',),
        ),
        migrations.CreateModel(
            name='CPitem',
            fields=[
                ('orderitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erp_main.orderitem')),
                ('personal_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cp', to='calculation.personalprice')),
            ],
            bases=('erp_main.orderitem',),
        ),
    ]
