# Generated by Django 5.2.8 on 2025-11-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_items', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalculationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('door_type', models.CharField(choices=[('internal', 'Межкомнатная'), ('external', 'Входная'), ('fire', 'Противопожарная'), ('armored', 'Бронированная')], default='internal', max_length=20)),
                ('status', models.IntegerField(choices=[(0, 'Черновик'), (1, 'На производстве'), (2, 'Готов к отгрузке'), (3, 'Отгружен'), (4, 'Отменен')], default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
