# Generated by Django 5.1.5 on 2025-03-12 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StandardPrice',
        ),
    ]
