# Generated by Django 5.1.5 on 2025-07-01 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculation', '0002_delete_standardprice'),
        ('erp_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_1', models.JSONField()),
                ('door_2', models.JSONField()),
                ('wide_door_1', models.JSONField()),
                ('hatch_1', models.JSONField()),
                ('wide_hatch_1', models.JSONField()),
                ('not_standard', models.JSONField()),
                ('gate', models.JSONField()),
                ('wide_gate', models.JSONField()),
                ('transom', models.JSONField()),
                ('dobor', models.JSONField()),
                ('door_panel', models.JSONField()),
                ('lock', models.JSONField()),
                ('handle', models.JSONField()),
                ('c_m', models.JSONField()),
                ('door_closer', models.JSONField()),
                ('metal', models.JSONField()),
                ('ral', models.JSONField()),
                ('vent_grate', models.JSONField()),
                ('plate', models.JSONField()),
                ('glass', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalPrice',
            fields=[
                ('standardprice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calculation.standardprice')),
                ('default_margin', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='erp_main.organization')),
            ],
            bases=('calculation.standardprice',),
        ),
    ]
