# Generated by Django 5.2.8 on 2026-02-09 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0002_initial'),
        ('erp_main', '0008_individualentrepreneur_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='project',
        ),
        migrations.AddField(
            model_name='calculation',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_main.organization'),
        ),
    ]
